#!/bin/bash

# ============================================
# Automated Hostinger Deployment Script
# ============================================
# This script automates the entire backend deployment
# Run with: bash auto-deploy-hostinger.sh

set -e  # Exit on error

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DOMAIN="tiftoapp.com"
SUBDOMAIN="api"
FULL_DOMAIN="${SUBDOMAIN}.${DOMAIN}"
APP_DIR="${HOME}/public_html/${SUBDOMAIN}"
BACKEND_REPO="https://github.com/Herookie7/ftifto-backend.git"
PORT=8001

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}🚀 Automated Hostinger Backend Deployment${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Step 1: Check prerequisites
echo -e "${YELLOW}📋 Step 1: Checking prerequisites...${NC}"

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js not found. Installing...${NC}"
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
fi
NODE_VERSION=$(node --version)
echo -e "${GREEN}✅ Node.js: $NODE_VERSION${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}❌ npm not found${NC}"
    exit 1
fi
NPM_VERSION=$(npm --version)
echo -e "${GREEN}✅ npm: $NPM_VERSION${NC}"

# Check git
if ! command -v git &> /dev/null; then
    echo -e "${YELLOW}⚠️  Git not found. Installing...${NC}"
    sudo apt-get update
    sudo apt-get install -y git
fi
echo -e "${GREEN}✅ Git installed${NC}"

# Check PM2
if ! command -v pm2 &> /dev/null; then
    echo -e "${YELLOW}⚠️  PM2 not found. Installing...${NC}"
    sudo npm install -g pm2
fi
PM2_VERSION=$(pm2 --version)
echo -e "${GREEN}✅ PM2: $PM2_VERSION${NC}"

echo ""

# Step 2: Create directory structure
echo -e "${YELLOW}📁 Step 2: Creating directory structure...${NC}"
mkdir -p "${APP_DIR}"
mkdir -p "${APP_DIR}/logs"
cd "${APP_DIR}"
echo -e "${GREEN}✅ Directory created: ${APP_DIR}${NC}"
echo ""

# Step 3: Clone or update repository
echo -e "${YELLOW}📥 Step 3: Setting up backend code...${NC}"
if [ -d ".git" ]; then
    echo "Repository exists, pulling latest changes..."
    git pull origin main || git pull origin master
else
    echo "Cloning repository..."
    git clone "${BACKEND_REPO}" .
fi
echo -e "${GREEN}✅ Code updated${NC}"
echo ""

# Step 4: Install dependencies
echo -e "${YELLOW}📦 Step 4: Installing dependencies...${NC}"
npm install --production
echo -e "${GREEN}✅ Dependencies installed${NC}"
echo ""

# Step 5: Generate JWT Secret
echo -e "${YELLOW}🔐 Step 5: Generating JWT Secret...${NC}"
JWT_SECRET=$(openssl rand -base64 32)
echo -e "${GREEN}✅ JWT Secret generated${NC}"
echo ""

# Step 6: Create .env file
echo -e "${YELLOW}📝 Step 6: Creating .env file...${NC}"

# Check if .env exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}⚠️  .env file exists. Backing up to .env.backup${NC}"
    cp .env .env.backup
fi

# Create .env file
cat > .env << EOF
# Auto-generated by deployment script
# Generated on: $(date)

# Required - MongoDB Connection
MONGO_URI=mongodb+srv://sunarthy7_db_user:kJ2fIdihzJfT3NGP@tifto-test.unnzzmz.mongodb.net/test

# Required - JWT Secret (auto-generated)
JWT_SECRET=${JWT_SECRET}

# Server Configuration
NODE_ENV=production
PORT=${PORT}

# API Configuration
API_BASE_URL=https://${FULL_DOMAIN}/api/v1
CORS_ORIGINS=https://${DOMAIN},https://www.${DOMAIN}

# Optional - Logging
LOG_LEVEL=combined

# Optional - Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX=100
EOF

echo -e "${GREEN}✅ .env file created${NC}"
echo -e "${BLUE}   Location: ${APP_DIR}/.env${NC}"
echo ""

# Step 7: Test MongoDB connection
echo -e "${YELLOW}🗄️  Step 7: Testing MongoDB connection...${NC}"
if node -e "
const mongoose = require('mongoose');
require('dotenv').config();
const mongoUri = process.env.MONGO_URI || process.env.MONGODB_URI;
if (!mongoUri) {
  console.error('MONGO_URI not found');
  process.exit(1);
}
mongoose.connect(mongoUri, { serverSelectionTimeoutMS: 5000 })
  .then(() => { console.log('Connected'); process.exit(0); })
  .catch(err => { console.error('Error:', err.message); process.exit(1); });
" 2>/dev/null; then
    echo -e "${GREEN}✅ MongoDB connection successful${NC}"
else
    echo -e "${RED}❌ MongoDB connection failed${NC}"
    echo -e "${YELLOW}   Please check:${NC}"
    echo "   1. MongoDB URI in .env is correct"
    echo "   2. Your server IP is whitelisted in MongoDB Atlas"
    echo "   3. MongoDB Atlas network access allows your IP"
fi
echo ""

# Step 8: Create PM2 ecosystem file
echo -e "${YELLOW}⚙️  Step 8: Creating PM2 configuration...${NC}"
cat > ecosystem.config.js << EOF
module.exports = {
  apps: [{
    name: 'ftifto-backend',
    script: './server.js',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: ${PORT}
    },
    error_file: './logs/pm2-error.log',
    out_file: './logs/pm2-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_memory_restart: '500M',
    watch: false,
    ignore_watch: ['node_modules', 'logs']
  }]
};
EOF
echo -e "${GREEN}✅ PM2 configuration created${NC}"
echo ""

# Step 9: Stop existing PM2 process (if any)
echo -e "${YELLOW}🛑 Step 9: Stopping existing processes...${NC}"
pm2 delete ftifto-backend 2>/dev/null || true
echo -e "${GREEN}✅ Cleaned up existing processes${NC}"
echo ""

# Step 10: Start with PM2
echo -e "${YELLOW}🚀 Step 10: Starting backend with PM2...${NC}"
pm2 start ecosystem.config.js
pm2 save
echo -e "${GREEN}✅ Backend started with PM2${NC}"
echo ""

# Step 11: Setup PM2 startup
echo -e "${YELLOW}⚙️  Step 11: Configuring PM2 startup...${NC}"
STARTUP_CMD=$(pm2 startup | grep -o 'sudo.*')
if [ ! -z "$STARTUP_CMD" ]; then
    echo -e "${YELLOW}   Run this command to enable PM2 on boot:${NC}"
    echo -e "${BLUE}   $STARTUP_CMD${NC}"
    echo ""
    read -p "Do you want to run this command now? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        eval $STARTUP_CMD
        echo -e "${GREEN}✅ PM2 startup configured${NC}"
    else
        echo -e "${YELLOW}⚠️  Please run the command manually later${NC}"
    fi
else
    echo -e "${YELLOW}⚠️  Could not generate startup command${NC}"
fi
echo ""

# Step 12: Display status
echo -e "${YELLOW}📊 Step 12: Checking status...${NC}"
sleep 2
pm2 status
echo ""

# Step 13: Test backend
echo -e "${YELLOW}🧪 Step 13: Testing backend...${NC}"
sleep 3

# Test local connection
if curl -s http://localhost:${PORT}/health > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Backend is running on port ${PORT}${NC}"
else
    echo -e "${YELLOW}⚠️  Backend might still be starting. Check logs:${NC}"
    echo -e "${BLUE}   pm2 logs ftifto-backend${NC}"
fi
echo ""

# Step 14: Get server IP
echo -e "${YELLOW}🌐 Step 14: Getting server information...${NC}"
SERVER_IP=$(curl -s ifconfig.me || curl -s ipinfo.io/ip || curl -s icanhazip.com)
if [ ! -z "$SERVER_IP" ]; then
    echo -e "${GREEN}✅ Server IP: ${SERVER_IP}${NC}"
    echo ""
    echo -e "${YELLOW}📋 DNS Configuration Required:${NC}"
    echo -e "${BLUE}   Go to Hostinger DNS / Nameservers${NC}"
    echo -e "${BLUE}   Add A record:${NC}"
    echo -e "${GREEN}     Type: A${NC}"
    echo -e "${GREEN}     Name: api${NC}"
    echo -e "${GREEN}     Points to: ${SERVER_IP}${NC}"
    echo -e "${GREEN}     TTL: 14400${NC}"
else
    echo -e "${YELLOW}⚠️  Could not detect server IP automatically${NC}"
    echo -e "${BLUE}   Please find your server IP from Hostinger panel${NC}"
fi
echo ""

# Summary
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✅ Deployment Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}📋 Summary:${NC}"
echo -e "   Backend Directory: ${APP_DIR}"
echo -e "   Backend URL: http://localhost:${PORT}"
echo -e "   Public URL: https://${FULL_DOMAIN} (after DNS setup)"
echo -e "   PM2 Process: ftifto-backend"
echo ""
echo -e "${YELLOW}📝 Next Steps:${NC}"
echo "   1. Configure DNS A record (see above)"
echo "   2. Wait 5-10 minutes for DNS propagation"
echo "   3. Setup SSL certificate:"
echo "      sudo certbot --nginx -d ${FULL_DOMAIN}"
echo "   4. Test: curl https://${FULL_DOMAIN}/health"
echo ""
echo -e "${YELLOW}🔧 Useful Commands:${NC}"
echo "   pm2 status                    # Check status"
echo "   pm2 logs ftifto-backend       # View logs"
echo "   pm2 restart ftifto-backend    # Restart"
echo "   pm2 monit                     # Monitor"
echo ""
echo -e "${GREEN}🎉 Your backend is now running!${NC}"
echo ""

