openapi: 3.0.3
info:
  title: Tifto Unified REST API
  description: Unified backend serving admin, seller, rider, and customer applications.
  version: 1.0.0
servers:
  - url: http://localhost:8001/api
    description: Local development
paths:
  /live:
    get:
      tags:
        - System
      summary: Liveness probe
      responses:
        '200':
          description: Service is live
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: live
  /ready:
    get:
      tags:
        - System
      summary: Readiness probe
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ready
  /v1/health:
    get:
      tags:
        - System
      summary: Health check
      description: Returns service availability status.
      responses:
        '200':
          description: Healthy response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /version:
    get:
      tags:
        - System
      summary: Backend version details
  /metrics:
    get:
      tags:
        - Monitoring
      summary: Prometheus metrics
      description: Exposes Prometheus-formatted service metrics.
      responses:
        '200':
          description: Metrics payload
          content:
            text/plain:
              schema:
                type: string
      responses:
        '200':
          description: Version payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: 1.0.0
                  commit:
                    type: string
                    example: 0123456789abcdef
  /v1/auth/login:
    post:
      tags:
        - Authentication
      summary: Login using email/phone and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - identifier
                - password
              properties:
                identifier:
                  type: string
                  description: Email or phone number
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials
  /v1/orders:
    get:
      tags:
        - Orders
      summary: List orders (admin/seller)
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
          description: Page size
      responses:
        '200':
          description: Orders page
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        role:
          type: string
          enum:
            - customer
            - seller
            - rider
            - admin

